### PR TITLE
feat(Arguments): cancel (button)

### PR DESCRIPTION
**Pull request by S222em**
**Please describe the changes this PR makes and why it should be merged:**
This PR adds a method to cancel an opened command prompt and adds buttons for non-boolean arguments. Buttons can be enabled with the `useButtons` option in the `GCommandsClient#commands` set to true.

image

image

Buttons lock when input is given. (buttons are quite large and change the positions of messages quite a bit)

**Status and versioning classification:**
- I know how to update typings and have done so, or typings don't need updating
- This PR changes the library's interface (methods or parameters added)

### CODE REVIEW

**Comment by xHyroM** [comment]
I would delete the support for useButtons to false.

**Comment by S222em** [comment]
@xHyroM done

**Comment by S222em** [comment]
Oh alright.

**Comment by S222em** [comment]
@xHyroM done again.

**Pull request merged**
