### PR TITLE
chore(7.0.0): 🐢

### PR DESCRIPTION
**Pull request by xHyroM**
**Please describe the changes this PR makes and why it should be merged:**

- [x] path
- [x] fix typings
- [x] fix eventloader
- [x] GError
- [x] French (missing typings)
- [x] userRequiredRoles fix
- [x] Collectors fix
- [x] ArgumentType typings
- [x] CommandBuilder
   https://github.com/Garlic-Team/GCommands/pull/145
- [x] @gcommands/voice
- [x] COMMAND_EXECUTE, COMMAND_ERROR change
- [x] SUB_COMMAND for normal args
   https://github.com/Garlic-Team/GCommands/pull/152
- [x] Gray slash cmds

**Status and versioning classification:**

- I know how to update typings and have done so, or typings don't need updating
- This PR changes the library's interface (methods or parameters added)

### CODE REVIEW

**Review by xHyroM — COMMENTED** [review]
a

**Review by xHyroM — COMMENTED** [review]
test only

**Comment by xHyroM** [comment]
🐢

**Comment by S222em** [comment]
@Gabe616 you forgot to update the CommandOptionsBuilder

**Comment by xHyroM** [comment]
> 
> 
> @Gabe616 you forgot to update the `CommandOptionsBuilder`, and the `Command` typings

fixed

**Pull request merged**
