### PR TITLE
feat: support for dynamic prefix & multiple prefixes

### PR DESCRIPTION
**Pull request by xhyrom**
**Please describe the changes this PR makes and why it should be merged:**
Support for dynamic message prefix & multiple prefixes

**Status and versioning classification:**
- This PR changes the library's interface (methods or parameters added)

### CODE REVIEW

**Review by S222em — APPROVED** [review]
One thing, Awaitable is not used anywhere else. Although we should start using it, I think we should stick to Promise for now

**Comment by xhyrom** [comment]
> One thing, Awaitable is not used anywhere else. Although we should start using it, I think we should stick to Promise for now

I don't know, I'd start slowly replacing it because it's pointless to force a person to have their function return `Promise<T>` when it doesn't have to.

```ts
export type Awaitable<T> = T | PromiseLike<T>

**Comment by xhyrom** [comment]
ill do some tests

**Comment by Robloxdude14** [comment]
Is this out

**Comment by xhyrom** [comment]
> Is this out

no, wait ill do test if it works

**Comment by xhyrom** [comment]
Okay, it works 👍

**Comment by xhyrom** [comment]
> Is this out

Released in next (development) version of gcommands `npm i gcommands@next`

**Pull request merged**
