### PR TITLE
chore(v8): 🎉

### PR DESCRIPTION
**Pull request by S222em**
**Please describe the changes this PR makes and why it should be merged:**

- [x] Remove support for discord.js v12
- [x] Improve loader
- [x] Fix command deletion
- [x] Better arguments collector
- [x] Sequelize
- [x] Slash and message commands use the [`CommandInteractionOptionResolver`](https://discord.js.org/#/docs/main/stable/class/CommandInteractionOptionResolver)
- [ ] Improve jsdocs
- [ ] V8 guide
- [x] Hyttpo #226 

**Status and versioning classification:**
- I know how to update typings and have done so, or typings don't need updating
- This PR changes the library's interface (methods or parameters added)
- This PR includes breaking changes (methods removed or renamed, parameters moved or removed)

### CODE REVIEW

**Review by ghost — CHANGES_REQUESTED** [review]
Is `objectArgs` deleted? If yes, please don't remove them in v8, it's useful :)

**Review by xhyrom — CHANGES_REQUESTED** [review]
objectArgs back 👍

**Comment by xHyroM** [comment]
I think djs also returns raw arguments, so you can use the getObjectArgs function from V70.

**Comment by S222em** [comment]
```js
const { Command, ArgumentType } = require("gcommands");

module.exports = class extends Command {
  constructor(client) {
    super(client, {
      name: 'test',
      description: 'test',
      guildOnly: '801033840059088897',
      args: [
        {
          name: 'boolean',
          description: 'another string',
          type: ArgumentType.BOOLEAN,
          required: true,
        },
        {
          name: 'user',
          description: 'another user',
          type: ArgumentType.USER,
          required: true,
        },
        {
          name: 'string',
          description: 'another string',
          type: ArgumentType.STRING,
          required: false,
        },
      ]
    });
  }

  async run({ respond, followUp, args, guild }) {
    // This returns a boolean named 'boolean'
    const boolean = args.getBoolean('boolean');

    // This returns a user named 'user'
    const user = args.getUser('user');

    // This returns a string named 'string'
    const string = args.getString('string');

    // This returns the raw data
    console.log(args.data);

    const msg = await respond({ content: `${boolean}: ${string}: ${user.username}` })
  }
}
```
This is currently working with bot slash and message commands. I don't see the point of the objectArgs anymore, because this is way better. It can return complete users, instead of just the userId.

**Comment by S222em** [comment]
@xHyroM csn you look above ^, and I can add `args.object` if your really want

**Comment by xHyroM** [comment]
(Protected branch issue resolved)

**Pull request closed without merging**
