### PR TITLE
fix(Command): command defaults

### PR DESCRIPTION
**Pull request by xhyrom**
**Please describe the changes this PR makes and why it should be merged:**

**Status and versioning classification:**

### CODE REVIEW

**Comment by xhyrom** [comment]
@garlic-team pack

**Review by S222em — CHANGES_REQUESTED** [review]
Shouldn't everything be changed to `||`?

**Comment by xhyrom** [comment]
> Shouldn't everything be changed to `||`?

No because other options are null by default

**Review by S222em — APPROVED** [review]

**Comment by xhyrom** [comment]
@garlic-team pack

**Pull request merged**
