### PR TITLE
feat!: support for djs v14

### LINKED ISSUE #536: djs v14 support
### Feature

Support for djs v14

### Ideal solution or implementation

Support for djs v14

### Alternative solutions or implementations

_No response_

### Other context

_No response_

### PR DESCRIPTION
**Pull request by xhyrom**
**Please describe the changes this PR makes and why it should be merged:**
> **Warning**
> Breaking changes, only djs v14 support due to types etc

> **Note**  
> If you want test this pr, use `npm i gcommands@pr-539 discord.js@latest`

gccommands v9.x.x will be still maintained (backports like djs)

**Status and versioning classification:**
- This PR includes breaking changes (methods removed or renamed, parameters moved or removed)

### CODE REVIEW

**Comment by xhyrom** [comment]
@garlic-team pack

**Comment by xhyrom** [comment]
@S222em

**Comment by xhyrom** [comment]
@garlic-team pack

**Comment by xhyrom** [comment]
@whattyu you can install this ^ (wait ~2min before)

**Comment by atatolgadln** [comment]
can you fix this if you are come back from vacation @xHyroM ⬎
import type { Interaction, InteractionType } from 'discord.js';
in [AutocompleteHandler.ts](https://github.com/Garlic-Team/gcommands/pull/539/commits/75becf60315eae00f6edb57d2e4804e4869da869), [ComponentHandler.ts](https://github.com/Garlic-Team/gcommands/pull/539/commits/6a72db14698c7c4d1ff12bebdb9912a261c39c68), [InteractionCommandHandler.ts](https://github.com/Garlic-Team/gcommands/pull/539/commits/f9fb1f57013ad0b5b0f0bdcd7ae99dbfa84040b6) because I get this error now⬎ [19:13:45/ERROR]  InteractionType is not defined

**Comment by xhyrom** [comment]
> can you fix this if you are come back from vacation @xHyroM ⬎ import type { Interaction, InteractionType } from 'discord.js'; in [AutocompleteHandler.ts](https://github.com/Garlic-Team/gcommands/pull/539/commits/75becf60315eae00f6edb57d2e4804e4869da869), [ComponentHandler.ts](https://github.com/Garlic-Team/gcommands/pull/539/commits/6a72db14698c7c4d1ff12bebdb9912a261c39c68), [InteractionCommandHandler.ts](https://github.com/Garlic-Team/gcommands/pull/539/commits/f9fb1f57013ad0b5b0f0bdcd7ae99dbfa84040b6) because I get this error now⬎ [19:13:45/ERROR] InteractionType is not defined

sorry for late response, ill check it

**Comment by xhyrom** [comment]
@garlic-team pack

**Review by S222em — COMMENTED** [review]
I think things like ArgumentType should be replaced by the ones from discord.js

**Comment by xhyrom** [comment]
> I think things like ArgumentType should be replaced by the ones from discord.js

Right, I'll deprecate ArgumentType enum

**Comment by xHyroM** [comment]
> I think things like ArgumentType should be replaced by the ones from discord.js

Right, I'll deprecate ArgumentType enum

**Comment by xhyrom** [comment]
@S222em could you test simple bot with this pr? im on vacation so if you have time please

**Comment by xhyrom** [comment]
Everything works, I must update component files

**Comment by xhyrom** [comment]
I'll merge this tomorrow

**Comment by xhyrom** [comment]
ill finish it today

**Comment by xhyrom** [comment]
@garlic-team pack

**Comment by xhyrom** [comment]
@garlic-team pack

**Pull request merged**
