### PR TITLE
new(Version): 4.1.1

### PR DESCRIPTION
**Pull request by xHyroM**
Install and test this RP:
```ssh
npm i Garlic-Team/GCommands
```

- [X] Nodejs 15+ support

### CODE REVIEW

**Comment by xHyroM** [comment]
Don't merge

**Comment by xHyroM** [comment]
https://github.com/Garlic-Team/GCommands/commit/b1e405cda4daa16ea0d7af4350ebe07025c6f61d

**Comment by xHyroM** [comment]
https://github.com/Garlic-Team/GCommands/commit/5e9ec04c221ed98ee5120f06afc263ff1b2622dd

**Comment by xHyroM** [comment]
^ no code break

**Comment by xHyroM** [comment]
guide https://github.com/Garlic-Team/GCommands/commit/8eec057926827b380fe8d9ca1072cfdff5d1d671

**Comment by xHyroM** [comment]
guide https://github.com/Garlic-Team/GCommands/commit/da0d0ac8402155359931f5d5f049dee7720561ed

**Comment by xHyroM** [comment]
https://github.com/Garlic-Team/GCommands/commit/355c3f43548d25459686b075d9e774ec870694d8

**Comment by xHyroM** [comment]
https://github.com/Garlic-Team/GCommands/commit/b635d2d406c244c5345a16f51d663e91cb1584be

**Comment by xHyroM** [comment]
https://github.com/Garlic-Team/GCommands/commit/b635d2d406c244c5345a16f51d663e91cb1584be

**Comment by xHyroM** [comment]
Buttons using discord-buttons with more changes and more support to gcommands

**Comment by xHyroM** [comment]
guide for easy inhibitor https://github.com/Garlic-Team/GCommands/commit/1297da4e7bcc989eb81b6417bd14ec176249675b 
https://gcommands.js.org/guide/miscellaneous/ownevents.html

**Comment by xHyroM** [comment]
guide for collectors https://github.com/Garlic-Team/GCommands/commit/714535e93d60d5fa1b45c9952e163859be40aac1

**Comment by xHyroM** [comment]
https://github.com/Garlic-Team/GCommands/commit/a8f17e57de1faf8d4875d48671068da63626e779 buttons page, collectors

**Review by xHyroM — COMMENTED** [review]
good

**Comment by xHyroM** [comment]
https://github.com/Garlic-Team/GCommands/commit/f6c9eee48a0e3ce51227420956855a99153f6d58

**Review by Gabe616 — COMMENTED** [review]
vrey nice

**Comment by xHyroM** [comment]
conflict fixed

**Comment by xHyroM** [comment]
waiting for review @SebestikCZ

**Review by SebestikCZ — APPROVED** [review]
Should be :)

**Review by Gabe616 — APPROVED** [review]
epic

**Comment by xHyroM** [comment]
guide https://github.com/Garlic-Team/GCommands/commit/d402fcc577de8adf98eac6fbe01e21912c44eedb

**Comment by xHyroM** [comment]
https://github.com/Garlic-Team/GCommands/commit/3a8cf2c103e4275f31612299fd456a9c58f8b34c

**Comment by xHyroM** [comment]
👍

**Pull request merged**
