### PR TITLE
Fix GMessage and Arguments

### PR DESCRIPTION
**Pull request by S222em**
**Please describe the changes this PR makes and why it should be merged:**
This PR adds the `alwaysObtain` option. If `alwaysObtain` is set to true, any arguments (excluding subcommand) will be asked again so the message can be multiple words, instead of just one.

Without `alwaysObtain` (if command has multiple arguments)
image

With `alwaysObtain` (if command has multiple arguments)
image

For commands with only 1 argument, all given arguments will be used instead of just one.

This PR also fixes an issue with `GMessage`, where the error (cannot send an empty message) would be displayed as another error.

**Status and versioning classification:**
- I know how to update typings and have done so, or typings don't need updating
- This PR changes the library's interface (methods or parameters added)

### CODE REVIEW

**Comment by S222em** [comment]
Wait what. 
image
I am a contributor now right? Now that some of my things are on the main branch?

**Comment by xHyroM** [comment]
Please set alwaysObtain to true (default)

**Comment by S222em** [comment]
Why would that be useful? It disallows input from the original message: `.test 1 2` won't work then. (for example)

**Comment by xHyroM** [comment]
> Why would that be useful? It disallows input from the original message: `.test 1 2` won't work then. (for example)
> 
> `alwaysObtain` is there for commands with multiple arguments, that require an input of multiple words (like a reason).
> 
> For commands like this
> `.ban <user> <reason>` without `alwaysObtain` will be a single word.

Okay

**Review by xHyroM — APPROVED** [review]

**Pull request merged**
