### PR TITLE
refactor: use @sapphire/shapeshift

### LINKED ISSUE #421: Use @sapphire/shapeshift
### Feature

`@sapphire/shapeshift` should be used instead of `zod`.

Shapeshift is a much faster validation library than `zod`, I did see the benchmarks somewhere but I can't find it anymore.

The API is mostly similar so it won't be a lot of work.

https://github.com/sapphiredev/shapeshift

### Ideal solution or implementation

Switch from `zod` to `@sapphire/shapeshift`

### Alternative solutions or implementations

Don't

### Other context

_No response_

### PR DESCRIPTION
**Pull request by S222em**
**Please describe the changes this PR makes and why it should be merged:**
#421 

**Status and versioning classification:**
None

### CODE REVIEW

**Comment by xhyrom** [comment]
v10?

**Comment by S222em** [comment]
> v10?

I still need to fix some things, probably an issue with shapeshift, so it probably wont be done in time for v9.2

**Comment by S222em** [comment]
I will take another look at the issue I have tomorrow and then decide if it will make v9.2.0, I think the issue I have currently is a issue with shapeshift, so it needs to get fixed and released on their side first. (Did not get to it, will do it soon)

**Comment by S222em** [comment]
Okay, so I finally looked at this. It seems like `AutoDeferType` is not actually exported from `GClient.ts` for some reason. It is listed correctly in the compiled code, but sadly it's still undefined, which throws an error. I am not sure how to magically make `AutoDeferType` be there so this might take a while to figure out.

**Pull request closed without merging**
