### PR TITLE
refactor: Plugins

### PR DESCRIPTION
**Pull request by S222em**
**Please describe the changes this PR makes and why it should be merged:**
This PR refactors inhibitors so that they more useful in several cases. Below is an example of how to use plugins now, and some internal systems have been changed/renamed to support/use this new system. These new plugins can provide better support for typescript, and adds more use cases in general, like a database of choice.
```ts
import { container, GClient, Plugin, PluginHookType } from 'gcommands';

new Plugin({
	name: 'some-plugin',
	[PluginHookType.AfterInitialization]: (client: GClient) => {
		container.somePlugin = client.options.somePlugin;
	},
});

declare module 'gcommands' {
        // add somePlugin to the client options
	interface GClientOptions {
		somePlugin: number;
	}
        // add somePlugin to the container
	interface Container {
		somePlugin: number;
	}
}
```

Yes, this system is inspired by @sapphire/framework plugin system.

**Status and versioning classification:**

- This PR changes the library's interface (methods or parameters added)
- This PR includes breaking changes (methods removed or renamed, parameters moved or removed)

### CODE REVIEW

**Comment by xhyrom** [comment]
I'll check it today/tomorrow.

**Comment by xhyrom** [comment]
First let's solve https://github.com/Garlic-Team/gcommands/pull/381 and after merging let's solve this PR

**Comment by xHyroM** [comment]
Resolve conflicts :D

**Review by xhyrom — COMMENTED** [review]
Please resolve conflicts

---

We've decided to keep this PR in on hold until djs v14 comes out so we don't add unnecessary work. While there aren't that many major changes and they are minor, we don't want to break it before djs v14 where there could be even more major changes in the case of this release.

**Pull request closed without merging**
