### PR TITLE
3.1.1

### PR DESCRIPTION
**Pull request by xHyroM**
- [x] channelOnly
- [x] Inhibitor
- [x] mention prefix

### CODE REVIEW

**Comment by xHyroM** [comment]
Don't merge now!

**Comment by xHyroM** [comment]
slash gui https://github.com/Garlic-Team/GCommands/commit/f2b3382373c8066498677699d2fb2b31d6f3b5dc

**Comment by xHyroM** [comment]
https://github.com/Garlic-Team/GCommands/commit/5f2abaddb1ebf44044f4a5ea8acf7154283dbaea

**Comment by xHyroM** [comment]
https://github.com/Garlic-Team/GCommands/commit/a4241be25b6ab6960e8fe34a5b06e140fd44b638

**Comment by xHyroM** [comment]
https://github.com/Garlic-Team/GCommands/commit/94c8c3fb63e3123c29c969e1bd263cc1e30bc342

**Comment by xHyroM** [comment]
https://github.com/Garlic-Team/GCommands/commit/3845ecd565224dd77a06a96fbad1197d196eecdd

**Comment by xHyroM** [comment]
https://docs.npmjs.com/about-semantic-versioning

**Comment by xHyroM** [comment]
https://gcommands.js.org/guide/additional/fromv2tov3.html

**Comment by xHyroM** [comment]
https://github.com/Garlic-Team/GCommands/commit/b46a68ee77423d598977b4a6a2e2896f8675b73c

**Comment by xHyroM** [comment]
guide https://github.com/Garlic-Team/GCommands/commit/610c2323b5320ceb4069534d35e9188135bc0d7d

**Comment by xHyroM** [comment]
guide https://github.com/Garlic-Team/GCommands/commit/fb986f87a56508fdc8e88dcf9cfcf079bd84e29b

**Comment by xHyroM** [comment]
https://github.com/Garlic-Team/GCommands/commit/3165838f2d5fb4ea15f4084ad572380e7ed1549e

**Comment by xHyroM** [comment]
https://github.com/Garlic-Team/GCommands/commit/c98ca691a6838093b7988a7c8bc3e3a588ed3bee

**Comment by xHyroM** [comment]
https://github.com/Garlic-Team/GCommands/commit/f94d5fba26741c9f07ab16309c89499fff4deadb

**Comment by xHyroM** [comment]
guide https://github.com/Garlic-Team/GCommands/commit/03401517d6c610df01872cd8bb09b5e2721dbcc7

**Comment by xHyroM** [comment]
guide https://github.com/Garlic-Team/GCommands/commit/3da924fb85780e40a7b461e46268b078617a091e

**Comment by xHyroM** [comment]
guide https://github.com/Garlic-Team/GCommands/commit/accd027e2b1c386472ca681d8e44c7056f812b95

**Review by Gabe616 — APPROVED** [review]
gűd

**Review by iZboxo — COMMENTED** [review]
ok

**Review by iZboxo — APPROVED** [review]
okm

**Comment by xHyroM** [comment]
docs https://github.com/Garlic-Team/GCommands/commit/acc20012e313045f5ab432f42a1a9c071d0f29d5

**Comment by xHyroM** [comment]
guide https://github.com/Garlic-Team/GCommands/commit/41c908fb7be9412ba1b20f2d33d9c70a68e9554e

**Comment by xHyroM** [comment]
waiting @SebestikCZ  for review

**Comment by SebestikCZ** [comment]
asi ok

**Review by SebestikCZ — APPROVED** [review]
I think, everything good.

**Comment by xHyroM** [comment]
Okay, merge 😄

**Comment by xHyroM** [comment]
https://github.com/Garlic-Team/GCommands/commit/accfd293586582c854765847e204c9b49d3b0558

**Pull request merged**
